language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
sudo: false
install:
  - test "${TRAVIS_RUST_VERSION//./_}" != "nightly" || rustup component add rustfmt-preview
script:
  - test "${TRAVIS_RUST_VERSION//./_}" != "nightly" || cargo fmt --all -- --check
  - cargo build --features "stub" --verbose
  - cargo test --features "stub" --verbose