language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
sudo: false
install:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo check --no-default-features --features stub
  - cargo build --features stub --verbose
  - cargo test --features stub --verbose --all