language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
script:
  - cargo build --feature "stub" --verbose
  - cargo test --feature "stub" --verbose