language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
sudo: false
install:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo build --features stub --verbose
  - cargo test --features stub --verbose --all