[package]
name = "deoxy"
version = "0.1.1"
authors = ["Alex Hamilton <alex.hamilton@ou.edu>"]
description = "A programmable, user-friendly buffer exchange system."
license = "ISC"

[dependencies]
gpio = "0.3.0"

[[bin]]
name = "deoxy"
doc = false
path = "src/main.rs"

[features]
default = []
stub = []