[package]
name = "deoxy"
version = "0.1.1"
authors = ["Alex Hamilton <alex.hamilton@ou.edu>"]
description = "A programmable, user-friendly buffer exchange system."
license = "ISC"

[dependencies]
gpio = "0.3.0"
toml = "0.4.5"

[[bin]]
name = "main"
doc = false
path = "src/main.rs"