[package]
name = "deoxy"
version = "0.1.1"
authors = ["Alex Hamilton <alex.hamilton@ou.edu>"]
description = "A programmable, user-friendly buffer exchange system."
license = "ISC"

[dependencies]
gpio = "0.3.0"
clap = "2.30.0"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4.5"

[[bin]]
name = "deoxy"
doc = false
path = "src/main.rs"

[features]
default = []
stub = []
