[package]
name = "deoxy"
version = "0.1.1"
authors = ["Alex Hamilton <alex.hamilton@ou.edu>"]
description = "A programmable, user-friendly buffer exchange system."
license = "ISC"
edition = "2018"

[[bin]]
name = "deoxy"
doc = false
path = "src/main.rs"

[dependencies.actix-web]
version = "0.7.18"
optional = true
[dependencies.gpio]
version = "0.4.1"
optional = true

[features]
default = ["full"]
full = ["actix-web", "gpio"] # Build full library (with threading and all)
stub = [] # Stub GPIO outputs for CI (where we can't access GPIO)
wasm = [] # Build just validation/user input components

[badges]
travis-ci = { repository = "aehmlo/deoxy", branch = "master" }
maintenance = { status = "actively-developed" }
