[[motors]]
pin = 4
range = [600, 2400] # µs
period = 20 # ms

[[motors]]
pin = 27
range = [600, 2400] # µs
period = 20 # ms

[[motors]]
pin = 21
range = [600, 2400] # µs
period = 20 # ms

[[motors]]
pin = 13
range = [600, 2400] # µs
period = 20 # ms

[[motors]]
pin = 26
range = [600, 2400] # µs
period = 20 # ms

[[motors]]
pin = 23
range = [600, 2400] # µs
period = 20 # ms

[[motors]]
pin = 22
range = [600, 2400] # µs
period = 20 # ms

[[motors]]
pin = 12
range = [600, 2400] # µs
period = 20 # ms

[[motors]]
pin = 20
range = [600, 2400] # µs
period = 20 # ms

[[motors]]
pin = 19
range = [600, 2400] # µs
period = 20 # ms

[pump]
pins = [24, 25, 5, 6]
flow-rate = 1000 # mL/min
invert = true
